export const qs=[
['Uma clínica precisa guardar pacientes, consultas e pagamentos em estruturas relacionadas. O que melhor atende a essa necessidade?',['Banco de dados','Editor de texto','Sistema operacional','Navegador','Compilador'],0],
['O software que cria, consulta e administra um banco de dados é chamado de:',['SGBD','Firewall','Editor gráfico','Sistema de arquivos','Driver'],0],
['Em uma tabela PRODUTO(id_produto, nome, preco), qual campo deve identificar unicamente cada produto?',['id_produto','nome','preco','a combinação nome e preco','nenhum'],0],
['Uma tabela VENDA possui id_venda, data e id_cliente. Se id_cliente aponta para CLIENTE.id_cliente, ele é uma:',['Chave estrangeira','Chave primária de VENDA','Índice obrigatório','Entidade','Tabela associativa'],0],
['Um cliente pode abrir várias solicitações, mas cada solicitação pertence a um cliente. A cardinalidade é:',['1:N','1:1','N:N','0:0','N:1 em ambos os sentidos'],0],
['Vários autores escrevem vários livros. Para representar esse relacionamento no modelo relacional, normalmente criamos:',['Uma tabela associativa AUTORIA','Um campo com todos os autores','Uma cópia da tabela LIVRO','Uma chave primária repetida','Nenhuma estrutura extra'],0],
['Na tabela PEDIDO, qual situação viola a integridade referencial?',['id_cliente=88 sem cliente 88 cadastrado','dois pedidos do mesmo cliente','nomes de produtos diferentes','preços com duas casas decimais','data preenchida'],0],
['Uma linha com id=7, nome="Rafa" e turma="2B" é um:',['Registro','Campo','SGBD','Banco','Relacionamento'],0],
['No modelo MER, “telefone” de CLIENTE é um:',['Atributo','Entidade','Relacionamento','SGBD','Registro'],0],
['Qual alternativa descreve uma boa prática ao escolher uma chave primária?',['Usar valor único e não nulo','Usar sempre o nome da pessoa','Permitir duplicatas','Deixá-la vazia quando possível','Usar qualquer texto repetido'],0],
['Em um sistema de biblioteca, qual operação CRUD corresponde a cadastrar um novo exemplar?',['INSERT','SELECT','UPDATE','DELETE','DROP'],0],
['Considere PRODUTO: (1, Cabo, 25), (2, Teclado, 80), (3, Monitor, 900). O que retorna SELECT nome FROM produto WHERE preco > 50?',['Teclado e Monitor','Cabo apenas','Os três produtos','Monitor apenas','Nenhum produto'],0],
['O comando UPDATE contas SET status="paga" WHERE id=14 altera:',['Somente a conta de id 14','Todas as contas','A tabela inteira','Nenhuma conta','A estrutura da tabela'],0],
['Se UPDATE estoque SET quantidade=0 for executado sem WHERE, assumindo execução bem-sucedida e sem gatilhos, o efeito provável é:',['Definir quantidade como 0 em todos os registros','Alterar somente o primeiro registro','Apagar a tabela','Criar uma coluna','Não alterar nada'],0],
['Para remover somente os registros de logs anteriores a 2024, o comando adequado é:',['DELETE FROM logs WHERE ano < 2024','DROP TABLE logs','DELETE DATABASE logs','UPDATE logs SET ano=2024','SELECT FROM logs'],0],
['Para armazenar o nome de um fornecedor, a data de entrega e a quantidade recebida, a combinação mais adequada é:',['VARCHAR, DATE e INT','DATE, INT e BOOLEAN','DECIMAL, VARCHAR e DATE','INT, DATE e VARCHAR','BOOLEAN, DECIMAL e INT'],0],
['Uma tabela repete endereço e telefone do mesmo cliente em centenas de pedidos. Separar CLIENTE e PEDIDO reduz principalmente:',['Redundância e inconsistências','A quantidade de chaves','A necessidade de consultas','A segurança do servidor','O número de registros válidos'],0],
['Qual opção caracteriza um banco orientado a documentos, como MongoDB?',['Armazena documentos com estrutura flexível','Exige apenas tabelas normalizadas','Usa somente planilhas','Não permite consultas','Armazena exclusivamente números'],0],
['Um índice criado na coluna usada frequentemente no WHERE tende a:',['Acelerar consultas, com custo de manutenção','Eliminar a necessidade de backup','Impedir INSERTs','Substituir a chave primária','Aumentar sempre o tamanho dos resultados'],0],
['Após uma falha no servidor, qual procedimento permite recuperar dados de uma cópia feita anteriormente?',['Restaurar um backup testado','Executar SELECT novamente','Criar um índice','Trocar VARCHAR por INT','Apagar registros duplicados'],0],
['Qual comando cria uma tabela nova?',['CREATE TABLE','INSERT','SELECT','UPDATE','DELETE'],0],
['Qual cláusula filtra registros em uma consulta?',['WHERE','VALUES','SET','TABLE','PRIMARY'],0],
['Qual comando lista todos os campos de clientes?',['SELECT * FROM clientes','INSERT clientes','UPDATE clientes','DELETE clientes','CREATE clientes'],0],
['Em SQL, valores de texto normalmente ficam entre:',['Aspas simples','Colchetes sempre','Parênteses duplos','Chaves','Barras'],0],
['Uma coluna que não aceita valor vazio pode ser definida como:',['NOT NULL','ONLY TEXT','NO VALUE','EMPTY','UNIQUE ROW'],0],
['A restrição UNIQUE serve para:',['Impedir valores repetidos','Apagar registros','Criar backups','Ordenar tabelas','Alterar tipos'],0],
['Qual tipo é adequado para indicar ativo ou inativo?',['BOOLEAN','DATE','VARCHAR','DECIMAL','BLOB'],0],
['O relacionamento entre pessoa e seu CPF geralmente é:',['1:1','1:N','N:N','0:N obrigatório','N:0'],0],
['Uma tabela associativa costuma conter:',['As chaves das duas tabelas relacionadas','Somente textos','Apenas uma coluna','Nenhuma chave','Arquivos de imagem'],0],
['Em um banco relacional, as tabelas se relacionam por meio de:',['Chaves','Parágrafos','Pastas','Slides','Imagens'],0],
['Qual atitude reduz o risco de perder dados?',['Fazer cópias de segurança periódicas','Desligar o servidor diariamente','Duplicar senhas','Remover índices','Usar nomes iguais'],0],
['O que é redundância de dados?',['Repetição desnecessária da mesma informação','Uma consulta rápida','Uma chave única','Um tipo numérico','Uma tabela vazia'],0],
['O comando INSERT normalmente é usado com:',['INSERT INTO e VALUES','WHERE e DELETE','SET e DROP','FROM e UPDATE','JOIN e CREATE'],0],
['Se id_produto é inteiro e único, ele é um bom exemplo de:',['Chave primária','Chave estrangeira','Atributo repetido','Índice textual','Registro'],0],
['A função de um SGBD inclui:',['Controlar acesso e manipular dados','Editar vídeos','Criar desenhos','Navegar na internet','Formatar textos'],0],
['Qual opção é um SGBD relacional?',['PostgreSQL','MongoDB','Photoshop','Chrome','Windows'],0],
['No modelo NoSQL de documentos, os dados podem ser organizados como:',['Documentos semelhantes a JSON','Somente linhas fixas','Apenas gráficos','Arquivos executáveis','Planilhas obrigatórias'],0],
['Ao usar DELETE com WHERE id=5, o objetivo é:',['Excluir o registro de id 5','Excluir a tabela inteira','Criar id 5','Alterar todos os registros','Consultar id 5'],0],
['A normalização facilita a manutenção porque:',['Organiza dados e evita inconsistências','Aumenta dados repetidos','Remove todas as relações','Impede consultas','Elimina chaves'],0],
['Uma escola precisa consultar os alunos em ordem alfabética pelo campo nome. Qual cláusula SQL deve usar?',['ORDER BY nome','DELETE nome','DROP nome','INSERT nome','UPDATE nome'],0]
];
export const classPrefixes={'2° ANO TÉCNICO MATUTINO':'MAT','2° ANO TÉCNICO VESPERTINO':'VESP','2° ANO TÉCNICO VESPERTINO NAZIR':'NAZIR','2° ANO TÉCNICO TRINDADE':'TRI2','1° ANO TÉCNICO TRINDADE':'TRI1'};
